### ISSUE TITLE
Connections from server itself?

### ISSUE THREAD

**Issue by Ranger21** [PassiveLemon/terraria-docker#1]
Im running server full of docker containers and i spun up this container, i see a lot of messages in logs like this, but i don't have anything on server what could be pointing to server port. Although, my server is debian proxmox lxc container with casaos and portainer installed

how do i find out what is trying to connect to my server? or is it just some sort of healthcheck of server itself?

127.0.0.1:47344 is connecting...
127.0.0.1:42896 is connecting...
127.0.0.1:36184 is connecting...
127.0.0.1:44168 is connecting...
127.0.0.1:33254 is connecting...
127.0.0.1:41234 is connecting...
127.0.0.1:44810 is connecting...
127.0.0.1:51102 is connecting...
127.0.0.1:34218 is connecting...
127.0.0.1:51678 is connecting...
127.0.0.1:41604 is connecting...
127.0.0.1:41054 is connecting...
127.0.0.1:58418 is connecting...
127.0.0.1:43918 is connecting...
127.0.0.1:34730 is connecting...
127.0.0.1:56342 is connecting...
127.0.0.1:33068 is connecting...
127.0.0.1:51614 is connecting...
127.0.0.1:56022 is connecting...
127.0.0.1:33976 is connecting...
127.0.0.1:34294 is connecting...
127.0.0.1:47878 is connecting...
127.0.0.1:37680 is connecting...
127.0.0.1:54524 is connecting...
127.0.0.1:45444 is connecting...
127.0.0.1:56992 is connecting...
127.0.0.1:58082 is connecting...
127.0.0.1:42480 is connecting...
127.0.0.1:44314 is connecting...
127.0.0.1:34640 is connecting...
127.0.0.1:53732 is connecting...
127.0.0.1:34700 is connecting...
127.0.0.1:38566 is connecting...
127.0.0.1:36158 is connecting...
127.0.0.1:41436 is connecting...
127.0.0.1:57350 is connecting...
127.0.0.1:42632 is connecting...
127.0.0.1:54324 is connecting...
127.0.0.1:49730 is connecting...
127.0.0.1:53486 is connecting...
127.0.0.1:43830 is connecting...
127.0.0.1:46594 is connecting...
127.0.0.1:34866 is connecting...
127.0.0.1:37402 is connecting...
127.0.0.1:50224 is connecting...
127.0.0.1:42154 is connecting...
127.0.0.1:49924 is connecting...
127.0.0.1:55358 is connecting...
127.0.0.1:56274 is connecting...
127.0.0.1:54418 is connecting...
127.0.0.1:55958 is connecting...
127.0.0.1:34974 is connecting...
127.0.0.1:36432 is connecting...
127.0.0.1:46410 is connecting...
127.0.0.1:32872 is connecting...
127.0.0.1:35242 is connecting...
127.0.0.1:36442 is connecting...
127.0.0.1:40156 is connecting...
127.0.0.1:43966 is connecting...
127.0.0.1:42870 is connecting...
127.0.0.1:39004 is connecting...
127.0.0.1:48272 is connecting...
127.0.0.1:37668 is connecting...
127.0.0.1:59830 is connecting...
127.0.0.1:43660 is connecting...
127.0.0.1:37140 is connecting...
127.0.0.1:41872 is connecting...
127.0.0.1:53804 is connecting...
127.0.0.1:41782 is connecting...
127.0.0.1:39274 is connecting...
127.0.0.1:39642 is connecting...
127.0.0.1:52320 is connecting...
127.0.0.1:39376 is connecting...
127.0.0.1:49674 is connecting...

**Comment by PassiveLemon** [comment]
It's the healthcheck for the container. It just TCP pings the server but I guess it's seen as a connection attempt to it's logged. If it bothers you enough, you could overwrite the healthcheck and that should stop those from appearing
