### ISSUE TITLE
World name and MOTD have their spaces turned into new lines

### ISSUE THREAD

**Issue by NariKraus** [PassiveLemon/terraria-docker#2]
autocreate=3
difficulty=2
banlist=banlist.txt
language=en-US
maxplayers=8
motd=Welcome
to
the
Pond
of
Dijon
Mustard.
We
hope
you
don't
drown.
npcstream=15
password=ananaB
port=7777
priority=1
seed=1369104
secure=1
upnp=0
worldname=The_Pond_of_Dijon_Mustard
world=/opt/terraria/config/Worlds/The_Pond_of_Dijon_Mustard.wld

**Comment by PassiveLemon** [comment]
Am able to reproduce, will look into it

**Comment by PassiveLemon** [comment]
Fixed in https://github.com/PassiveLemon/terraria-docker/commit/ee349aba30f7dc42a4f9d73027e37579634e6e0c
